### ISSUE TITLE
extends keyword highlighted as misued when valid

### ISSUE THREAD

**Issue by rui-nibau** [jefferyto/gtksourceview-js-lang#2]
Hello.

Thanks for this work. It looks promising.

I found a little hint when using customElements API :

`customElements.define('custom-name', CustomClass, {extends: 'article'});`

"extends" is here highlighted as misused but it is not : [customElements.define](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define) allows "extends" keyword as a option.

Maybe hard to address it. We can bypass this using quotes for object properties declaration.

Regards,

**Comment by jefferyto** [comment]
Thanks for filing this (and for trying these definitions)!

I checked the [spec](https://tc39.es/ecma262/#sec-object-initializer); turns out reserved words (`extends`, `class`, etc.) are allowed as property names for all object literals.

I've made the change in master, would be great if you can give a try :smile:

Thanks again!

**Comment by rui-nibau** [comment]
hello.

Yes, it works well :-).

Thanks.
